# config/settings.yaml
model:
  llm: qwen-plus
  temperature: 0.7
  embedding: text-embedding-v2

vectorstore:
  collection_name: example_collection
  persist_directory: ./chroma_db

web:
  urls:
    - https://lilianweng.github.io/posts/2023-06-23-agent/
  bs_kwargs:
    parse_only:
      class: ["post-content", "post-title", "post-header"]

text_splitter:
  chunk_size: 1000
  chunk_overlap: 200

rag:
  prompt: rlm/rag-prompt